#!/usr/bin/env bash

nicenumber() {
    separator="$(echo $1 | sed 's/[[:digit:]]//g')"
    if [ ! -z "$separator" -a "$separator" != "$DD" ] ; then
        echo "$0: Unknown decimal separator $separator encountered." >&2
        exit 1
    fi

    integer=$(echo $1 | cut -d "$DD" -f1)
    decimal=$(echo $1 | cut -d "$DD" -f2)

    if [ "$decimal" != $1 ] ; then
        result="${DD:="."}$decimal"
    fi

    thousands=$integer

    while [ $thousands -gt 999 ]; do
        remainder=$(($thousands % 1000))

        while [ ${#remainder} -lt 3 ]; do
            remainder="0$remainder"
        done

        result="${TD:=","}${remainder}${result}"
        thousands=$(($thousands / 1000))
    done

    nicenum="${thousands}${result}"

    if [ ! -z $2 ] ; then
        echo $nicenum
    fi
}

# default value
DD="."
TD=","

while getopts "d:t:" opt; do
    case $opt in
        d) DD="$OPTARG" ;;
        t) TD="$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))

if [ $# -eq 0 ] ; then
    echo "Usage: $(basename $0) [-d c] [-t c] numeric_value"
    echo " -d specifies the decimal point delimiter (default '.')"
    echo " -t specifies the thousands delimiter (default ',')"
    exit 0
fi

# nicenumber $1 1

value=$(nicenumber $1 1)
echo -e "\e[1;33mDo you really want to pay \$$value?\e[0m"

exit 0
